import type { MetadataRoute } from "next";

// Web app manifest → installable on the counter device, launches
// standalone/fullscreen in landscape. Icons are placeholders generated by
// scripts/gen-icons.mjs; swap for a designed logo before launch.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Cachier POS",
    short_name: "Cachier",
    description: "Supermarket point of sale",
    start_url: "/",
    display: "standalone",
    orientation: "landscape",
    background_color: "#ffffff",
    theme_color: "#18181b",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
