import type { MetadataRoute } from "next";

// Web app manifest → installable on the counter device, launches
// standalone on desktop (Windows/Mac/Linux) and mobile (Android/iOS). Icons are placeholders generated by
// scripts/gen-icons.mjs; swap for a designed logo before launch.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Cachier POS",
    short_name: "Cachier",
    description: "Supermarket point of sale",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    display_override: ["window-controls-overlay", "standalone"],
    // phones use it portrait for manager tools; the counter device stays landscape by hardware
    orientation: "any",
    categories: ["business", "shopping"],
    background_color: "#ffffff",
    theme_color: "#18181b",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
